gokins:
  jenkins-url: http://localhost:8080/
  job:
    - id: 1005
      # 配置 jenkins 的任务名称
      name: test-job
      # 执行前是否需要确认
      ack: true
      # 执行前确认的提示文字，当 ack=true 时有效，默认提示为【是否确认部署？(y/N)：】
      ack-text: "此任务将部署生产环境，是否确认部署？(y/N)："
      params:
        - name: git_branch
          value: master
        - name: maven_cmd
          value: "clean install"
      # gokins ls 命令显示的提示信息
      columns:
        - name: id
          value: 1005
        - name: project
          value: "项目名称"
        - name: branch
          value: master
        - name: env
          value: test
        - name: ack
          value: true
        - name: description
          value: "任务描述信息、备注等"